### ISSUE TITLE
Can this be made compatible with lua-http?

### ISSUE THREAD

**Issue by ryanford** [leafo/lua-mailgun#3]
Can this be made to check for http.compat.socket for lua-http support?

**Comment by leafo** [comment]
I looked over the code real quick an it looks like you can pass `http_provider` to the constructor:

```diff
 local m = Mailgun({
   domain = "leafo.net",
   api_key = "api:key-blah-blah-blahblah",
+  http_provider = require("http.compat.socket")
 })
```

**Comment by ryanford** [comment]
Works fine with this. Thanks
